name: "Doohicky"
description: "a site about nothing"
signature: "Yours truly, Grizzly Bear"
highlighter: rouge
# drop the extension when generating permalinks, for redirect_from and indexes
permalink: "/:categories/:year/:month/:day"
markdown: kramdown
# change this if you are accessing your site from a non-root path. 
baseurl: '/'
# enables "edit" and "create page" links
github:
  # example for a user or organization site
  # name: 'GRIZZLYBEAR'
  # project 'GRIZZLYBEAR.github.io'
  # branch: master

  # example for a project site
  name: 'edrex'
  project: 'reusable-jekyll-site'
  branch: 'gh-pages'
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
prose:
  siteurl: http://reusable-jekyll-site.pdxhub.org
  # needed for prose "insert page link" feature
  # relativeLinks: 'http://GRIZZLYBEAR.github.io/links.jsonp'
  relativeLinks: 'http://reusable-jekyll-site.pdxhub.org/links.jsonp'
  # uncomment to limit editing to the _posts directory
  #rooturl: '_posts'
  media: 'media'
  metadata:
    "":
      - name: permalink
        field:
          label: Permalink
          element: "text"
          help: override the default path
      - name: redirect_from
        field:
          label: Redirect from
          element: "text"
          help: redirect from this path to the current page
      - name: redirect_to
        field:
          label: Redirect to
          element: "text"
          help: redirect the current page to this URL
    _posts:
      - name: description
        field:
          label: Description
          element: "text"
          help: Displayed in the post listing
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Honey"
              value: "honey"
            - name: "Salmon"
              value: "salmon"
            - name: "Huckleberries"
              value: "huckleberries"
